{ config, pkgs, lib, ... }:

let
  # 1. Generate Assets using Python/Pillow
  hyperRecoveryThemeAssets = pkgs.runCommand "hyper-recovery-theme-assets" {
    nativeBuildInputs = [ pkgs.python3 pkgs.python3Packages.pillow ];
    src = ./scripts/generate_theme_assets.py;
    fonts = ./assets/fonts;
  } ''
    mkdir -p $out/grub $out/plymouth
    
    # Create a working directory
    mkdir work
    cd work
    
    # Copy script
    cp $src generate_assets.py
    
    # Copy fonts
    mkdir -p assets/fonts
    cp $fonts/* assets/fonts/
    
    # Patch script to output to current directory
    sed -i 's|BASE_DIR = Path(__file__).resolve().parent.parent|BASE_DIR = Path(".")|' generate_assets.py
    
    # Run script (outputs to ./assets/grub and ./assets/plymouth)
    python3 generate_assets.py
    
    # Install
    cp assets/grub/* $out/grub/
    cp assets/plymouth/* $out/plymouth/
  '';

  # 2. Snosu Plymouth Theme Package
  snosuPlymouthTheme = pkgs.stdenv.mkDerivation {
    pname = "snosu-hyper-recovery-plymouth";
    version = "1.0";
    src = ./snosu-hyper-recovery;
    fontSrc = ./assets/fonts/undefined-medium/undefined-medium.ttf;
    
    installPhase = ''
      mkdir -p $out/share/plymouth/themes/snosu-hyper-recovery
      cp -r * $out/share/plymouth/themes/snosu-hyper-recovery
      
      # Copy font to theme directory
      cp $fontSrc $out/share/plymouth/themes/snosu-hyper-recovery/undefined-medium.ttf
      
      # Fix permissions if needed
      chmod -R +w $out/share/plymouth/themes/snosu-hyper-recovery
    '';
  };

  # 3. Snosu GRUB Theme Package
  snosuGrubTheme = pkgs.stdenv.mkDerivation {
    pname = "snosu-hyper-recovery-grub";
    version = "1.0";
    src = ./snosu-hyper-recovery/grub;
    fontSrc = ./assets/fonts/undefined-medium/undefined-medium.ttf;
    
    nativeBuildInputs = [ pkgs.grub2 ];
    
    installPhase = ''
      mkdir -p $out
      cp * $out/
      
      # Convert Fonts
      # GRUB requires PF2 fonts. We generate them in required sizes.
      # The font name inside the PF2 will be "Undefined Medium <size>"
      # We need to match what's in theme.txt or update theme.txt
      
      grub-mkfont -s 12 -o $out/undefined_medium_12.pf2 $fontSrc
      grub-mkfont -s 14 -o $out/undefined_medium_14.pf2 $fontSrc
      grub-mkfont -s 16 -o $out/undefined_medium_16.pf2 $fontSrc
      grub-mkfont -s 24 -o $out/undefined_medium_24.pf2 $fontSrc
      
      # Update theme.txt to match the actual font name generated by grub-mkfont
      # Usually "Undefined Medium 16"
      sed -i 's/Hyper Street Fighter 2 Regular/Undefined Medium/g' $out/theme.txt
      sed -i 's/Hyper Fighting Regular/Undefined Medium/g' $out/theme.txt
    '';
  };

in
{
  # ZFS Support
  boot.supportedFilesystems = [ "zfs" "exfat" "vfat" ];
  boot.zfs.forceImportRoot = false;
  networking.hostId = "8425e349";

  # Kernel & Hardware
  # Use default LTS kernel for smaller size and better stability
  boot.kernelPackages = pkgs.linuxPackages;
  
  # Quiet Boot & Splash
  boot.kernelParams = [ 
    "quiet" 
    "splash" 
    "loglevel=3" 
    "rd.systemd.show_status=false" 
    "rd.udev.log_level=3" 
    "udev.log_priority=3" 
    "vt.global_cursor_default=0"
  ];
  
  # Disable documentation to save space (~100MB)
  documentation.enable = false;
  documentation.nixos.enable = false;
  documentation.man.enable = false;
  documentation.doc.enable = false;
  documentation.info.enable = false;
  
  # Hypervisor & Virtualization
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      # Use a minimal QEMU package (host architecture only) to save ~300MB+
      package = pkgs.qemu_kvm;
      # Run as root to ensure access to raw block devices (/dev/sdX)
      runAsRoot = true;
      swtpm.enable = true;
    };
  };

  # Cockpit Management
  services.cockpit = {
    enable = true;
    openFirewall = true;
    settings = {
      WebService = {
        AllowUnencrypted = true;
        Branding = "snosu";
        # Explicitly allow root login
        AllowRoot = true;
      };
    };
  };

  environment.etc."cockpit/branding/snosu/branding.ini".source = ./branding/snosu/branding.ini;
  environment.etc."cockpit/branding/snosu/branding.css".source = ./branding/snosu/branding.css;
  environment.etc."cockpit/branding/snosu/logo.png".source = ./branding/snosu/logo.png;
  environment.etc."cockpit/branding/snosu/apple-touch-icon.png".source = ./branding/snosu/logo.png;
  environment.etc."cockpit/branding/snosu/favicon.ico".source = ./branding/snosu/logo.png;
  
  environment.etc."motd".text =
    (builtins.readFile ./assets/motd-logo.ansi)
    + ''

    Welcome to Snosu Hyper Recovery Environment

    * Access the Web UI at: https://<IP>:9090
    * Default user: root / nixos
    * To start recovery, use the 'zpool import' command.

  '';
  
  environment.etc."issue".text = ''
    Snosu Hyper Recovery Environment
    \l
  '';
  
  environment.systemPackages = with pkgs; [
    cockpit
    cockpit-machines
    cockpit-zfs
    cockpit-files # File Manager for Cockpit
    qemu-utils
    virt-manager
    zfs
    parted
    gptfdisk
    htop
    vim
    git
    pciutils
    usbutils
    smartmontools
    nvme-cli
    os-prober
    efibootmgr
    wpa_supplicant
    dhcpcd
    udisks # Required for Cockpit Storage tab
    
    (pkgs.writeShellScriptBin "import-proxmox-pools" ''
      #!/bin/sh
      echo "Scanning for ZFS pools..."
      sudo zpool import
      
      echo ""
      echo "To import a pool, run: sudo zpool import -f <poolname>"
      echo "The -f flag is often needed if the pool was not cleanly exported (e.g. crash/power loss)."
      echo "Proxmox pools are typically named 'rpool'."
    '')
  ];

  # Networking
  networking.networkmanager.enable = true;
  networking.firewall.enable = false;
  networking.hostName = "snosu-hyper-recovery";
  networking.extraHosts = ''
    127.0.0.1 localhost
    127.0.1.1 snosu-hyper-recovery snosu-hr
  '';

  # Enable UDisks2 for Cockpit Storage management
  services.udisks2.enable = true;

  # Nix Configuration
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # User Configuration
  users.users.root.password = "nixos";
  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "yes";
  };

  # Ensure Plymouth works in the initrd
  boot.initrd.systemd.enable = true;
  boot.initrd.kernelModules = [ "loop" "isofs" ];

  systemd.services.save-boot-logs = {
    description = "Save boot logs to Ventoy USB";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-journald.service" "local-fs.target" ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutStartSec = "30";
      ExecStart = pkgs.writeShellScript "save-boot-logs" ''
        set -euo pipefail

        labels=("VENTOY" "Ventoy" "ventoy")
        device=""
        for label in "''${labels[@]}"; do
          if [ -e "/dev/disk/by-label/$label" ]; then
            device="/dev/disk/by-label/$label"
            break
          fi
        done

        if [ -z "$device" ]; then
          exit 0
        fi

        mkdir -p /mnt/ventoy
        if ! mountpoint -q /mnt/ventoy; then
          mount -o rw "$device" /mnt/ventoy || exit 0
        fi

        log_dir="/mnt/ventoy/boot-logs"
        mkdir -p "$log_dir"

        journalctl -b -o short-precise > "$log_dir/journal.txt" || true
        dmesg -T > "$log_dir/dmesg.txt" || true

        if [ -f /run/plymouth/plymouth-debug.log ]; then
          cp /run/plymouth/plymouth-debug.log "$log_dir/plymouth-debug.log"
        fi

        sync
      '';
    };
  };

  # Note: The ISO generator uses 'system.nixos.distroName' + 'system.nixos.label' + appendToMenuLabel
  # We can try to override distroName to be empty or "Hyper Recovery"
  system.nixos.distroName = "";
  system.nixos.label = "";

  boot.loader.grub.memtest86.enable = false;

  # Add custom GRUB entries for Drive 1/2 and Other
  # Note: 'boot.loader.grub.extraEntries' does NOT work for the ISO image itself, only installed system.
  # The ISO generation logic is in 'nixos/modules/installer/cd-dvd/iso-image.nix'.
  # It doesn't easily support custom entries without forking the module.
  # BUT, we can use the ISO-specific module to style it.
  
  boot.loader.grub.extraEntries = ''
    menuentry "Boot from First Hard Disk" {
      chainloader (hd0)+1
    }
    menuentry "Boot from Second Hard Disk" {
      chainloader (hd1)+1
    }
    submenu "Other" {
      menuentry "Reboot" {
        reboot
      }
      menuentry "Power Off" {
        halt
      }
    }
  '';
  
  # GRUB Theme (EFI)
  boot.loader.grub = {
    enable = true;
    version = 2;
    device = "nodev";
    efiSupport = true;
    theme = snosuGrubTheme;
    # We point to the file inside the theme package
    splashImage = "${snosuGrubTheme}/background.png";
  };

  # Plymouth Theme
  boot.plymouth = {
    enable = true;
    theme = "snosu-hyper-recovery";
    themePackages = [ snosuPlymouthTheme ];
  };

}
