{ config, pkgs, lib, ... }:

let
  # 1. Generate Assets using Python/Pillow
  hyperRecoveryThemeAssets = pkgs.runCommand "hyper-recovery-theme-assets" {
    nativeBuildInputs = [ pkgs.python3 pkgs.python3Packages.pillow ];
    src = ./scripts/generate_theme_assets.py;
    fonts = ./assets/fonts;
  } ''
    mkdir -p $out/grub $out/plymouth
    
    # Create a working directory
    mkdir work
    cd work
    
    # Copy script
    cp $src generate_assets.py
    
    # Copy fonts
    mkdir -p assets/fonts
    cp $fonts/* assets/fonts/
    
    # Patch script to output to current directory
    sed -i 's|BASE_DIR = Path(__file__).resolve().parent.parent|BASE_DIR = Path(".")|' generate_assets.py
    
    # Run script (outputs to ./assets/grub and ./assets/plymouth)
    python3 generate_assets.py
    
    # Install
    cp assets/grub/* $out/grub/
    cp assets/plymouth/* $out/plymouth/
  '';

  # 2. Snosu Plymouth Theme Package
  snosuPlymouthTheme = pkgs.stdenv.mkDerivation {
    pname = "snosu-hyper-recovery-plymouth";
    version = "1.0";
    src = ./snosu-hyper-recovery;
    
    installPhase = ''
      mkdir -p $out/share/plymouth/themes/snosu-hyper-recovery
      cp -r * $out/share/plymouth/themes/snosu-hyper-recovery
      # Fix permissions if needed
      chmod -R +w $out/share/plymouth/themes/snosu-hyper-recovery
    '';
  };

  # 3. Snosu GRUB Theme Package
  snosuGrubTheme = pkgs.stdenv.mkDerivation {
    pname = "snosu-hyper-recovery-grub";
    version = "1.0";
    src = ./snosu-hyper-recovery/grub;
    fontSrc = ./assets/fonts/hyper-street-fighter-2-color.colr.ttf/hyper-street-fighter-2-color.colr.ttf;
    
    nativeBuildInputs = [ pkgs.grub2 ];
    
    installPhase = ''
      mkdir -p $out
      cp * $out/
      
      # Convert Fonts
      # GRUB requires PF2 fonts. We generate them in required sizes.
      # The font name inside the PF2 will be "Hyper Street Fighter 2 Regular <size>"
      # We need to match what's in theme.txt or update theme.txt
      
      grub-mkfont -s 12 -o $out/hyper_fighting_12.pf2 $fontSrc
      grub-mkfont -s 14 -o $out/hyper_fighting_14.pf2 $fontSrc
      grub-mkfont -s 16 -o $out/hyper_fighting_16.pf2 $fontSrc
      grub-mkfont -s 24 -o $out/hyper_fighting_24.pf2 $fontSrc
      
      # Update theme.txt to match the actual font name generated by grub-mkfont
      # Usually "Hyper Street Fighter 2 Regular 16"
      sed -i 's/Hyper Fighting Regular/Hyper Street Fighter 2 Regular/g' $out/theme.txt
    '';
  };

in
{
  # ZFS Support
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.forceImportRoot = false;
  networking.hostId = "8425e349";

  # Kernel & Hardware
  # Use default LTS kernel for smaller size and better stability
  boot.kernelPackages = pkgs.linuxPackages;
  
  # Disable documentation to save space (~100MB)
  documentation.enable = false;
  documentation.nixos.enable = false;
  documentation.man.enable = false;
  documentation.doc.enable = false;
  documentation.info.enable = false;
  
  # Hypervisor & Virtualization
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      # Use a minimal QEMU package (host architecture only) to save ~300MB+
      package = pkgs.qemu_kvm;
      # Run as root to ensure access to raw block devices (/dev/sdX)
      runAsRoot = true;
      swtpm.enable = true;
    };
  };

  # Cockpit Management
  services.cockpit = {
    enable = true;
    openFirewall = true;
    settings = {
      WebService = {
        AllowUnencrypted = true;
        Branding = "snosu";
        # Explicitly allow root login
        AllowRoot = true;
      };
    };
  };

  environment.etc."cockpit/branding/snosu/branding.ini".source = ./branding/snosu/branding.ini;
  environment.etc."cockpit/branding/snosu/branding.css".source = ./branding/snosu/branding.css;
  environment.etc."cockpit/branding/snosu/logo.png".source = ./branding/snosu/logo.png;
  environment.etc."cockpit/branding/snosu/apple-touch-icon.png".source = ./branding/snosu/logo.png;
  environment.etc."cockpit/branding/snosu/favicon.ico".source = ./branding/snosu/logo.png;
  
  environment.etc."motd".text = ''
    
     ██████╗ ██╗   ██╗███████╗██████╗ ███████╗     ██╗███╗   ██╗██╗  ██╗███████╗██████╗ ███████╗
    ██╔════╝ ██║   ██║██╔════╝██╔══██╗██╔════╝     ██║████╗  ██║██║ ██╔╝██╔════╝██╔══██╗██╔════╝
    ██║  ███╗██║   ██║█████╗  ██████╔╝█████╗       ██║██╔██╗ ██║█████╔╝ █████╗  ██████╔╝█████╗  
    ██║   ██║██║   ██║██╔══╝  ██╔══██╗██╔══╝       ██║██║╚██╗██║██╔═██╗ ██╔══╝  ██╔══██╗██╔══╝  
    ╚██████╔╝╚██████╔╝███████╗██║  ██║███████╗     ██║██║ ╚████║██║  ██╗███████╗██║  ██║███████╗
     ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝     ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝
    
    Welcome to Snosu Hyper Recovery Environment
    
    * Access the Web UI at: https://<IP>:9090
    * Default user: root / nixos
    * To start recovery, use the 'zpool import' command.
    
  '';
  
  environment.etc."issue".text = ''
    Snosu Hyper Recovery Environment
    \l
  '';
  
  environment.systemPackages = with pkgs; [
    cockpit
    cockpit-bridge
    cockpit-machines
    cockpit-zfs
    qemu-utils
    virt-manager
    zfs
    parted
    gptfdisk
    htop
    vim
    git
    pciutils
    usbutils
    smartmontools
    nvme-cli
    os-prober
    efibootmgr
    wpa_supplicant
    dhcpcd
    
    (pkgs.writeShellScriptBin "import-proxmox-pools" ''
      #!/bin/sh
      echo "Scanning for ZFS pools..."
      sudo zpool import
      
      echo ""
      echo "To import a pool, run: sudo zpool import -f <poolname>"
      echo "The -f flag is often needed if the pool was not cleanly exported (e.g. crash/power loss)."
      echo "Proxmox pools are typically named 'rpool'."
    '')
  ];

  # Networking
  networking.networkmanager.enable = true;
  networking.firewall.enable = false;
  networking.hostName = "snosu-recovery";
  networking.extraHosts = ''
    127.0.0.1 localhost
    127.0.1.1 snosu-recovery
  '';

  # Nix Configuration
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # User Configuration
  users.users.root.password = "nixos";
  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "yes";
  };

  # ISO Specifics
  # Maximize compression (slower build, smaller ISO)
  isoImage.squashfsCompression = "zstd -Xcompression-level 19";

  # Set the ISO filename
  isoImage.isoName = "snosu-hyper-recovery-x86_64-linux.iso";
  
  # Use custom GRUB theme for the ISO bootloader
  isoImage.grubTheme = snosuGrubTheme;
  isoImage.splashImage = "${snosuGrubTheme}/background.png";
  
  # Ensure Plymouth works in the ISO initrd
  boot.initrd.systemd.enable = true;
  
  # Rename the default installer entry
  isoImage.prependToMenuLabel = "START HYPER RECOVERY";
  isoImage.appendToMenuLabel = ""; # Clear default
  
  # Note: The ISO generator uses 'system.nixos.distroName' + 'system.nixos.label' + appendToMenuLabel
  # We can try to override distroName to be empty or "Hyper Recovery"
  system.nixos.distroName = "Hyper Recovery";
  system.nixos.label = ""; # Clear version label if desired
  
  # Add custom GRUB entries for Drive 1/2 and Other
  # Note: 'boot.loader.grub.extraEntries' does NOT work for the ISO image itself, only installed system.
  # The ISO generation logic is in 'nixos/modules/installer/cd-dvd/iso-image.nix'.
  # It doesn't easily support custom entries without forking the module.
  # BUT, we can use 'isoImage.grubTheme' to style it, which we did.
  
  # Workaround: We can't easily change the structure of the ISO menu without patching nixpkgs.
  # However, we can use 'isoImage.syslinuxTheme' for BIOS.
  # For EFI (GRUB), we are stuck with the default layout unless we patch.
  
  # Let's try to use 'boot.loader.grub.extraEntries' just in case it gets picked up by some versions,
  # or if we are talking about the installed system.
  # But for the ISO, we might have to accept the default "NixOS Installer" or "START HYPER RECOVERY" (via label).
  
  boot.loader.grub.extraEntries = ''
    menuentry "Boot from First Hard Disk" {
      chainloader (hd0)+1
    }
    menuentry "Boot from Second Hard Disk" {
      chainloader (hd1)+1
    }
    submenu "Other" {
      menuentry "Reboot" {
        reboot
      }
      menuentry "Power Off" {
        halt
      }
    }
  '';
  
  # GRUB Theme (EFI)
  boot.loader.grub = {
    enable = true;
    version = 2;
    device = "nodev";
    efiSupport = true;
    theme = snosuGrubTheme;
    # We point to the file inside the theme package
    splashImage = "${snosuGrubTheme}/background.png";
  };

  # Plymouth Theme
  boot.plymouth = {
    enable = true;
    theme = "snosu-hyper-recovery";
    themePackages = [ snosuPlymouthTheme ];
  };

  # Syslinux Menu (BIOS)
  isoImage.syslinuxTheme = lib.mkForce ''
    DEFAULT boot
    TIMEOUT 100
    PROMPT 1
    
    UI menu.c32
    
    MENU TITLE Hypervisor OS Boot CD
    
    LABEL boot
      MENU LABEL START HYPER RECOVERY
      LINUX /boot/bzImage
      APPEND init=${config.system.build.toplevel}/init ${toString config.boot.kernelParams} initrd=/boot/initrd

    LABEL disk1
      MENU LABEL Boot from First Hard Disk (hd0)
      COM32 chain.c32
      APPEND hd0
      
    LABEL disk2
      MENU LABEL Boot from Second Hard Disk (hd1)
      COM32 chain.c32
      APPEND hd1
      
    MENU BEGIN Other
      MENU TITLE Other Options
      
      LABEL reboot
        MENU LABEL Reboot
        COM32 reboot.c32
        
      LABEL poweroff
        MENU LABEL Power Off
        COM32 poweroff.c32
    MENU END
  '';
}
